// <auto-generated/>
#pragma warning disable 1591
#pragma warning disable 0414
#pragma warning disable 0649
#pragma warning disable 0169

namespace EAD_CA2_Crypto.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "C:\Users\aaron\EAD-CA2\EAD-CA2-Crypto\_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\aaron\EAD-CA2\EAD-CA2-Crypto\_Imports.razor"
using System.Net.Http.Json;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "C:\Users\aaron\EAD-CA2\EAD-CA2-Crypto\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "C:\Users\aaron\EAD-CA2\EAD-CA2-Crypto\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "C:\Users\aaron\EAD-CA2\EAD-CA2-Crypto\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "C:\Users\aaron\EAD-CA2\EAD-CA2-Crypto\_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "C:\Users\aaron\EAD-CA2\EAD-CA2-Crypto\_Imports.razor"
using Microsoft.AspNetCore.Components.WebAssembly.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "C:\Users\aaron\EAD-CA2\EAD-CA2-Crypto\_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "C:\Users\aaron\EAD-CA2\EAD-CA2-Crypto\_Imports.razor"
using EAD_CA2_Crypto;

#line default
#line hidden
#nullable disable
#nullable restore
#line 10 "C:\Users\aaron\EAD-CA2\EAD-CA2-Crypto\_Imports.razor"
using EAD_CA2_Crypto.Shared;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "C:\Users\aaron\EAD-CA2\EAD-CA2-Crypto\Pages\CryptoDetail.razor"
using System.Linq;

#line default
#line hidden
#nullable disable
    [Microsoft.AspNetCore.Components.RouteAttribute("/crypto/{cryptoId:int}")]
    public partial class CryptoDetail : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
        }
        #pragma warning restore 1998
#nullable restore
#line 108 "C:\Users\aaron\EAD-CA2\EAD-CA2-Crypto\Pages\CryptoDetail.razor"
       
    [Parameter]
    public int cryptoId { get; set; }
    private bool isSortedAscending;
    private string activeSortColumn;
    private Root[] cryptos;
    private MarketRoot[] cryptoMarkets;

    protected override async Task OnInitializedAsync()
    {
        string getURL = $"https://api.coinlore.net/api/ticker/?id={cryptoId}";
        cryptos = await Http.GetFromJsonAsync<Root[]>(getURL);

        string getMarketURL = $"https://api.coinlore.net/api/coin/markets/?id={cryptoId}";
        cryptoMarkets = await Http.GetFromJsonAsync<MarketRoot[]>(getMarketURL);
    }

    public class Root
    {
        public string id { get; set; }
        public string symbol { get; set; }
        public string name { get; set; }
        public string nameid { get; set; }
        public int rank { get; set; }
        public string price_usd { get; set; }
        public string percent_change_24h { get; set; }
        public string percent_change_1h { get; set; }
        public string percent_change_7d { get; set; }
        public string market_cap_usd { get; set; }
        public string volume24 { get; set; }
        public string volume24_native { get; set; }
        public string csupply { get; set; }
        public string price_btc { get; set; }
        public string tsupply { get; set; }
        public string msupply { get; set; }
    }

    public class MarketRoot
    {
        public string name { get; set; }
        public string @base { get; set; }
        public string quote { get; set; }
        public double? price { get; set; }
        public double? price_usd { get; set; }
        public double? volume { get; set; }
        public double? volume_usd { get; set; }
        public int? time { get; set; }
    }

    private void SortTable(string columnName)
    {
        if (columnName != activeSortColumn)
        {
            cryptoMarkets = cryptoMarkets.OrderBy(x => x.GetType().GetProperty(columnName).GetValue(x, null)).ToArray();
            isSortedAscending = true;
            activeSortColumn = columnName;
        }
        else
        {
            if (isSortedAscending)
            {
                cryptoMarkets = cryptoMarkets.OrderByDescending(x => x.GetType().GetProperty(columnName).GetValue(x, null)).ToArray();
            }
            else
            {
                cryptoMarkets = cryptoMarkets.OrderBy(x => x.GetType().GetProperty(columnName).GetValue(x, null)).ToArray();
            }
            isSortedAscending = !isSortedAscending;
        }
    }

    private string SetSortIcon(string columnName)
    {
        if (activeSortColumn != columnName)
        {
            return string.Empty;
        }
        if (isSortedAscending)
        {
            return "fa-sort-up";
        }
        else
        {
            return "fa-sort-down";
        }
    }

#line default
#line hidden
#nullable disable
        [global::Microsoft.AspNetCore.Components.InjectAttribute] private HttpClient Http { get; set; }
    }
}
#pragma warning restore 1591
