// <auto-generated/>
#pragma warning disable 1591
#pragma warning disable 0414
#pragma warning disable 0649
#pragma warning disable 0169

namespace EAD_CA2_Crypto.Pages
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "C:\Users\aaron\EAD-CA2\EAD-CA2-Crypto\_Imports.razor"
using System.Net.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\aaron\EAD-CA2\EAD-CA2-Crypto\_Imports.razor"
using System.Net.Http.Json;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "C:\Users\aaron\EAD-CA2\EAD-CA2-Crypto\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "C:\Users\aaron\EAD-CA2\EAD-CA2-Crypto\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "C:\Users\aaron\EAD-CA2\EAD-CA2-Crypto\_Imports.razor"
using Microsoft.AspNetCore.Components.Web;

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "C:\Users\aaron\EAD-CA2\EAD-CA2-Crypto\_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization;

#line default
#line hidden
#nullable disable
#nullable restore
#line 7 "C:\Users\aaron\EAD-CA2\EAD-CA2-Crypto\_Imports.razor"
using Microsoft.AspNetCore.Components.WebAssembly.Http;

#line default
#line hidden
#nullable disable
#nullable restore
#line 8 "C:\Users\aaron\EAD-CA2\EAD-CA2-Crypto\_Imports.razor"
using Microsoft.JSInterop;

#line default
#line hidden
#nullable disable
#nullable restore
#line 9 "C:\Users\aaron\EAD-CA2\EAD-CA2-Crypto\_Imports.razor"
using EAD_CA2_Crypto;

#line default
#line hidden
#nullable disable
#nullable restore
#line 10 "C:\Users\aaron\EAD-CA2\EAD-CA2-Crypto\_Imports.razor"
using EAD_CA2_Crypto.Shared;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "C:\Users\aaron\EAD-CA2\EAD-CA2-Crypto\Pages\Index.razor"
using System.Linq;

#line default
#line hidden
#nullable disable
    [Microsoft.AspNetCore.Components.RouteAttribute("/")]
    public partial class Index : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
        }
        #pragma warning restore 1998
#nullable restore
#line 66 "C:\Users\aaron\EAD-CA2\EAD-CA2-Crypto\Pages\Index.razor"
       
    private Root cryptos;
    private Root filteredCryptos;
    private bool isSortedAscending;
    private string activeSortColumn;

    protected override async Task OnInitializedAsync()
    {
        //retrieving the top 100 cryptos from the api to display in the table
        cryptos = await Http.GetFromJsonAsync<Root>("https://api.coinlore.net/api/tickers/?start=0&limit=100");
        //creating a duplicate of the cryptos for filtering
        filteredCryptos = cryptos;
    }

    public class Datum
    {
        public string id { get; set; }
        public string symbol { get; set; }
        public string name { get; set; }
        public string nameid { get; set; }
        public int rank { get; set; }
        public string price_usd { get; set; }
        public string percent_change_24h { get; set; }
        public string percent_change_1h { get; set; }
        public string percent_change_7d { get; set; }
        public string price_btc { get; set; }
        public string market_cap_usd { get; set; }
        public double volume24 { get; set; }
        public double volume24a { get; set; }
        public string csupply { get; set; }
        public string tsupply { get; set; }
        public string msupply { get; set; }
    }

    public class Info
    {
        public int coins_num { get; set; }
        public int time { get; set; }
    }

    public class Root
    {
        public List<Datum> data { get; set; }
        public Info info { get; set; }
    }

    //taking the input from the search field and filtering through the list to find the cryptos that contain the search, sending a get request again to reset cryptos.
    private async void OnSearchTextChange(ChangeEventArgs changeEventArgs)
    {
        string searchText = changeEventArgs.Value.ToString();
        filteredCryptos.data = cryptos.data.Where(crypto => crypto.name.Contains(searchText)).ToList();
        cryptos = await Http.GetFromJsonAsync<Root>("https://api.coinlore.net/api/tickers/?start=0&limit=100");
    }

    private void SortTable(string columnName)
    {
        if (columnName != activeSortColumn)
        {
            //ordering the filtered cryptos by ascending order if clicked on for the first time
            filteredCryptos.data = filteredCryptos.data.OrderBy(crypto => crypto.GetType().GetProperty(columnName).GetValue(crypto, null)).ToList();
            isSortedAscending = true;
            activeSortColumn = columnName;
        }
        else
        {
            if (isSortedAscending)
            {
                filteredCryptos.data = filteredCryptos.data.OrderByDescending(crypto => crypto.GetType().GetProperty(columnName).GetValue(crypto, null)).ToList();
            }
            else
            {
                filteredCryptos.data = filteredCryptos.data.OrderBy(crypto => crypto.GetType().GetProperty(columnName).GetValue(crypto, null)).ToList();
            }
            isSortedAscending = !isSortedAscending;
        }
    }

    //Setting an icon in the column header
    private string SetSortIcon(string columnName)
    {
        if (activeSortColumn != columnName)
        {
            return string.Empty;
        }
        if (isSortedAscending)
        {
            return "fa-sort-up";
        }
        else
        {
            return "fa-sort-down";
        }
    }

#line default
#line hidden
#nullable disable
        [global::Microsoft.AspNetCore.Components.InjectAttribute] private HttpClient Http { get; set; }
    }
}
#pragma warning restore 1591
